### PR TITLE
added back missing csv files

### PR DESCRIPTION
**Pull request by stephaniaa**
Header and source files were missing for the csv code I did yesterday (think i accidentally deleted them) so i've added back in

### CODE REVIEW

**Comment by edbrax** [comment]
Interesting. See that sounds like it could have been a version control issue - something went wrong with the git process. Very similar thing happened to me a couple of times last semester, and Ian (the guy that runs the startup) told me last week one of their programs suddenly just stopped working. He needs to get the guy who wrote it to come back in to check it out, but he thinks this is a git issue as well. This is what I mean about how git might be better than nothing, but it's along way short of a good version control system. No matter how smart people might believe Linus Torvalds to be.

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
Actually I was thinking it might be because I didn’t commit the changes to the .pro.user file? Ill try committing those changes next time and see if it keeps my files there in the edit tab in qt

**Comment by edbrax** [comment]
Hmm. Do you mean you didn't save the project on your local computer before you merged it up to the remote?

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
No I did save it but when I create a new branch and change my git to reflect that branch it is opening up that branch in qt isn’t it?

**Comment by edbrax** [comment]
Yes. So let's sort out exactly the order of events. When you created the CSV header and source files yesterday, you saved that project on your local computer, then you committed the changes on the local computer, then you merged that branch back up to the remote master (origin/master)?

Then today you created a new branch in the remote repo that was based on the master, then you fetched that branch down to local and found the CSV header and source files were missing when you opened the local repo in Qt?

You said you copied the CSV header and source files back in? But where did you copy those files from and to?

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
Yep that order is right I think.
So the commit I did just now I commited the .pro.user file and all the header and source files were there so I think it’s fixed the issue

**Pull request merged**
